<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tcontent\Module'                        => __DIR__ . '/Module.php',
    'Tcontent\Controller\IndexController' => __DIR__ . '/src/Tcontent/Controller/IndexController.php',
);
