<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Training\Module'                        => __DIR__ . '/Module.php',
    'Training\Controller\IndexController' => __DIR__ . '/src/Training/Controller/IndexController.php',
    'Training\Controller\ContentController' => __DIR__ . '/src/Training/Controller/ContentController.php',
);
