	<div class="control seccion_titulo">
                <?php if (  \Util\UserSession::isAddPrivilege() || \Util\UserSession::isEditPrivilege() ){ ?>
            <div style="text-align: right;">
            <span id="update_web_button"><a href="http://nutrifami.org/util/jobs/update-capacitacion-json" target="background" class="update_web">Update WEB</a></span>
            </div>
		<?php } ?>
		<h3><a>Trainings</a> <?php echo $this->breadcrumbs; ?></h3>
		<?php if (  \Util\UserSession::isAddPrivilege() ){ ?>
		  <a href="add" class="add">New Training</a>
		<?php } ?>
	</div>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="training_table">
		<thead>
            <tr>
            	<th>Id</th>
                <th>Titulo</th>
                <th>Descripci&oacute;n</th>
                <th>Idioma</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
		
	</table>

<script>
    var editorTrainings; 
    
    $(document).ready(function() {
              
        var table = $('#training_table').dataTable( {
            "processing": true,
            "serverSide": true,
            "ajax": "<?php echo $this->serverUrl()?>/training/content/get-list",
            "columns": [
                { data: "cap_id", "visible": false },
                { data: "cap_titulo" },
                { data: "cap_descripcion" },
                { data: "cap_idioma"} ,
                { data: "cap_status" },
                { data: null,
                  "orderable": false,
                  className: "right",
                  defaultContent: '<?php if (  \Util\UserSession::isEditPrivilege() ){ ?><a href="javascript:void(0);" alt="Modules" title="Modules" class="modules"></a> <a href="javascript:void(0);" alt="Editar" title="Editar" class="edit"></a> <?php } ?><?php if (  \Util\UserSession::isDeletePrivilege() ){ ?><a href="javascript:void(0);" alt="Eliminar" title="Eliminar" class="delete"></a> <?php } ?>'
                }
            ],
            "iDisplayLength": 10
        } );      
        
        
        
        $('#training_table').on( 'click', 'a.modules', function () {
        var data = table.fnGetData($(this).parents('tr'));
        $(location).attr('href',"/tcontent/modules/list?cid="+data['cap_id']);
        
        
    } );
              
    $('.update_web').click(function(){
         $('#update_web_button').html('Cargando...');
    });          
    
              
    });
    
    
</script>