<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Util\Module'                        => __DIR__ . '/Module.php',
    'Util\Controller\IndexController' => __DIR__ . '/src/Util/Controller/IndexController.php',
    'UtilTest\Framework\TestCase'        => __DIR__ . '/tests/Util/Framework/TestCase.php',
    'UtilTest\SampleTest'                => __DIR__ . '/tests/Util/SampleTest.php',
);
