	<div class="control">
            <h3><a href="list">M&oacute;dulos</a> / <a href="javascript:void(0);"><?php echo $this->module['mod_titulo']; ?> / <a href="javascript:void(0);">Lecciones</a></a></h3>
		<?php if (  \Util\UserSession::isAddPrivilege() ){ ?>
		  <a href="add?mid=<?php echo $this->mid; ?>" class="add">Nueva Lección</a>
		<?php } ?>
	</div>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="modules_table">
		<thead>
            <tr>
            	<th>Id</th>
                <th>Titulo</th>
                <th>Descripci&oacute;n</th>
                <th>Imagen</th>
                <th>Fecha</th>
                <th></th>
            </tr>
        </thead>
		
	</table>
<script>
var editorModules; // use a global for the submit and return data rendering in the examples
 
$(document).ready(function() {
	
	var table = $('#modules_table').dataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "<?php echo $this->serverUrl()?>/tcontent/modules/get-list?pid=<?php echo $this->pid; ?>",
        "columns": [
            { data: "mod_id", "visible": false },
            { data: "mod_titulo" },
            { data: "mod_descripcion" },
            { data: "mod_imagen" },
            { data: "mod_fecha" },
            { data: null,
              "orderable": false,
              className: "right",
              defaultContent: '<?php if (  \Util\UserSession::isEditPrivilege() ){ ?><a href="javascript:void(0);" alt="Lecciones" title="Lecciones" class="lessons"></a> <a href="javascript:void(0);" alt="Editar" title="Editar" class="edit"></a> <?php } ?><?php if (  \Util\UserSession::isDeletePrivilege() ){ ?><a href="javascript:void(0);" alt="Eliminar" title="Eliminar" class="delete"></a> <?php } ?>'
            }
        ],
        "iDisplayLength": 10
    } ); 
	
	editorModules = new $.fn.dataTable.Editor( {
        ajax: "<?php echo $this->serverUrl()?>/tcontent/modules/update-row",
        table: "#modules_table",
        idSrc:  'mod_id',
        fields: [ {
	                label: "Id:",
	                name: "mod_id"
	            }, {
	                label: "Titulo:",
	                name: "mod_titulo"
	            }, {
	                label: "Descripci&oacute;n:",
	                name: "mod_descripcion"
	            }, {
	                label: "Imagen:",
	                name: "mod_imagen"
	            }, {
	                label: "Fecha:",
	                name: "mod_fecha"
	            }
	        ]
	    } );
	
	// Activate an inline edit on click of a table cell
    $('#modules_table').on( 'click', 'td', function (e) { 
        editorModules.inline( this , {
            submitOnBlur: true
        });
    } );

    $('#modules_table').on( 'click', 'a.delete', function () {
    	var data = table.fnGetData($(this).parents('tr'));
        if ( confirm("Se eliminara el elemento. Desea continuar?") == true ){
            $(location).attr('href',"delete?id="+data['mod_id']);
        }
    } );

    $('#modules_table').on( 'click', 'a.edit', function () {
        var data = table.fnGetData($(this).parents('tr'));
        $(location).attr('href',"edit?id="+data['mod_id']);
    } );
    
      
} );
</script>