	<div class="control">
		<h3><a href="list">Kits</a></h3>
		<?php if (  \Util\UserSession::isAddPrivilege() ){ ?>
		  <a href="add" class="add">Nuevo Producto</a>
		<?php } ?>
	</div>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="kits_table">
		<thead>
            <tr>
            	<th>Id</th>
                <th>Nombre</th>
                <th>Descripci&oacute;n</th>
                <th>Unidad</th>
                <th>Cantidad</th>
                <th>Precio / Unidad</th>
                <th></th>
            </tr>
        </thead>
	</table>
<script>

</script>