<?php if ($this->error): ?>
    <div class="error">User or password incorrect</div>
<?php endif; ?>


<?php
$form = $this->form;
$form->setAttribute('action', 'enter');
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formRow($form->get('username')) . PHP_EOL;
echo $this->formRow($form->get('password')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

