<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tfrances\Module'                        => __DIR__ . '/Module.php',
    'Tfrances\Controller\IndexController' => __DIR__ . '/src/Tfrances/Controller/IndexController.php',
);
