<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Twayuu\Module'                        => __DIR__ . '/Module.php',
    'Twayuu\Controller\IndexController' => __DIR__ . '/src/Twayuu/Controller/IndexController.php',
);
