<strong>Module:</strong>        Util &raquo;
<strong>Controller:</strong>    Index &raquo;
<strong>Action:</strong>        test-s3

<br>

<p>

    <input type="file" id="file-chooser" /> 
    <input type="text" id="file-location" />
    <button id="upload-button">Upload to S3</button>
    <div id="file-name"></div>
    
</p>

<script type="text/javascript">

  nutrifami_aws.s3.load();

  var fileChooser = document.getElementById('file-chooser');
  var button = document.getElementById('upload-button');
  var results = document.getElementById('file-name');
  button.addEventListener('click', function() {
      var newFile = fileChooser.files[0];
      var fileName = getFileName(newFile.name);
      var fileLocation = document.getElementById('file-location').value;
      results.innerHTML = fileName;
      nutrifami_aws.s3.uploadFile(newFile,fileLocation,fileName);
  });
   
</script>