<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tawa\Module'                        => __DIR__ . '/Module.php',
    'Tawa\Controller\IndexController' => __DIR__ . '/src/Tawa/Controller/IndexController.php',
);
