	<div class="control seccion_titulo">
            <h3><a href="/tcontent/modules/list">Modules</a> / <a href="/tcontent/lessons/list?mid=<?php echo $this->module['mod_id']; ?>"><?php echo $this->module['mod_titulo']; ?> / <a href="javascript:void(0);"><?php echo $this->lesson['lec_titulo']; ?></h3>
		<?php if (  \Util\UserSession::isAddPrivilege() ){ ?>
		  <a href="add?mid=<?php echo $this->mid; ?>&lid=<?php echo $this->lid; ?>" class="add">New Element</a>
		<?php } ?>
	</div>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="unidades_table">
		<thead>
            <tr>
            	<th>Id</th>
                <th>Type</th>
                <th>Instruction</th>
                <th>Instruction Audio</th>
                <th>Title/Question</th>
                <th>Image</th>
                <th>Audio</th>
                <th>Order</th>
                <th></th>
            </tr>
        </thead>
		
	</table>
<script>
var editorUnidades; // use a global for the submit and return data rendering in the examples
 
$(document).ready(function() {
	
	var table = $('#unidades_table').dataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "<?php echo $this->serverUrl()?>/tcontent/unidadinformacion/get-list?lid=<?php echo $this->lid; ?>",
        "columns": [
            { data: "uni_inf_id", "visible": false },
            { data: "uni_inf_tip_icono", 
              "render": function(data, type, row) {
                    return '<img width="60" src="/img/icons/'+data+'" />';
                }
            },
            { data: "uni_inf_instruccion" },
            { data: "uni_inf_instruccion_audio", 
              "render": function(data, type, row) {
                    return '<audio controls><source src="https://s3.amazonaws.com/nutrifami/'+data+'" type="audio/mpeg">Explorador no reproduce audio</audio>';
                }
            },
            { data: "uni_inf_titulo" },
            { data: "uni_inf_imagen", 
              "render": function(data, type, row) {
                    if (data != ''){
                        return '<img width="100" src="https://s3.amazonaws.com/nutrifami/'+data+'" />';
                    }else {
                        return '';
                    }
                }
            },
            { data: "uni_inf_audio", 
              "render": function(data, type, row) {
                    return '<audio controls><source src="https://s3.amazonaws.com/nutrifami/'+data+'" type="audio/mpeg">Explorador no reproduce audio</audio>';
                }
            },
            { data: "lec_ele_orden",
                "render": function(data, type, row){
                    return '<p style="text-align: center">'+data+'</p>'
                }
            },
            { data: null,
              "orderable": false,
              className: "right",
              defaultContent: '<?php if (  \Util\UserSession::isEditPrivilege() ){ ?><a href="javascript:void(0);" alt="Options or answers" title="Options or answers" class="options"></a> <a href="javascript:void(0);" alt="Edit" title="Edit" class="edit"></a> <?php } ?><?php if (  \Util\UserSession::isDeletePrivilege() ){ ?><a href="javascript:void(0);" alt="Delete" title="Delete" class="delete"></a> <?php } ?>'
            }
        ],
        "iDisplayLength": 10
    } ); 
    
    
    editorUnidades = new $.fn.dataTable.Editor( {
        ajax: "<?php echo $this->serverUrl()?>/tcontent/unidadinformacion/update-row",
        table: "#unidades_table",
        idSrc:  'uni_inf_id',
        fields: [{
                    label: "Id:",
	            name: "uni_inf_id"
	        }, {
                    label: "Titulo:",
	            name: "uni_inf_titulo"
	        }, {
	            label: "Orden:",
	            name: "lec_ele_orden"
	        }
	        ]
	    } );
	
	// Activate an inline edit on click of a table cell
    $('#unidades_table').on( 'click', 'td', function (e) { 
        editorUnidades.inline( this , {
            submitOnBlur: true
        });
    } );
    
    
    $('#unidades_table').on( 'click', 'a.edit', function () {
        var data = table.fnGetData($(this).parents('tr'));
        $(location).attr('href',"edit?id="+data['uni_inf_id']+"&mid="+<?php echo $this->mid; ?>+"&lid="+<?php echo $this->lid; ?>);
    } );
    
    
    $('#unidades_table').on( 'click', 'a.delete', function () {
    	var data = table.fnGetData($(this).parents('tr'));
        if ( confirm("This element will be deleted. Do you want continue?") == true ){
            $(location).attr('href',"delete?id="+data['uni_inf_id']+"&mid="+<?php echo $this->mid; ?>+"&lid="+<?php echo $this->lid; ?>);
        }
    } );
    
    $('#unidades_table').on( 'click', 'a.options', function () {
        var data = table.fnGetData($(this).parents('tr'));
        $(location).attr('href',"../unidadopcion/list?uid="+data['uni_inf_id']+"&lid="+<?php echo $this->lid; ?>+"&mid="+<?php echo $this->mid; ?>);
    } );
    
      
} );
</script>