	<div class="control seccion_titulo">
            <h3><a href="list">M&oacute;dulos</a> / <a href="javascript:void(0);"><?php echo $this->module['mod_titulo']; ?> / <a href="javascript:void(0);"><?php echo $this->lesson['lec_titulo']; ?> / <a href="javascript:void(0);">Preguntas</a></a></h3>
		<?php if (  \Util\UserSession::isAddPrivilege() ){ ?>
		  <a href="add?mid=<?php echo $this->mid; ?>&lid=<?php echo $this->lid; ?>" class="add">Nuevo Elemento</a>
		<?php } ?>
	</div>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="unidades_table">
		<thead>
            <tr>
            	<th>Id</th>
                <th>Tipo</th>
                <th>Instrucción</th>
                <th>Audio Instrucción</th>
                <th>Titulo/Pregunta</th>
                <th>Imagen</th>
                <th>Audio</th>
                <th>Orden</th>
                <th></th>
            </tr>
        </thead>
		
	</table>
<script>
var editorUnidades; // use a global for the submit and return data rendering in the examples
 
$(document).ready(function() {
	
	var table = $('#unidades_table').dataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": "<?php echo $this->serverUrl()?>/tcontent/unidadinformacion/get-list?lid=<?php echo $this->lid; ?>",
        "columns": [
            { data: "uni_inf_id", "visible": false },
            { data: "uni_inf_tip_icono", 
              "render": function(data, type, row) {
                    return '<img width="60" src="/img/icons/'+data+'" />';
                }
            },
            { data: "uni_inf_instruccion" },
            { data: "uni_inf_instruccion_audio", 
              "render": function(data, type, row) {
                    return '<audio controls style="width: 80px;"><source src="https://s3.amazonaws.com/nutrifami/'+data+'" type="audio/mpeg">Explorador no reproduce audio</audio>';
                }
            },
            { data: "uni_inf_titulo" },
            { data: "uni_inf_imagen", 
              "render": function(data, type, row) {
                    if (data != ''){
                        return '<img width="100" src="https://s3.amazonaws.com/nutrifami/'+data+'" />';
                    }else {
                        return '';
                    }
                }
            },
            { data: "uni_inf_audio", 
              "render": function(data, type, row) {
                    return '<audio controls style="width: 80px;"><source src="https://s3.amazonaws.com/nutrifami/'+data+'" type="audio/mpeg">Explorador no reproduce audio</audio>';
                }
            },
            { data: "lec_ele_orden" },
            { data: null,
              "orderable": false,
              className: "right",
              defaultContent: '<?php if (  \Util\UserSession::isEditPrivilege() ){ ?><a href="javascript:void(0);" alt="Opciones y/o respuestas" title="Opciones y/o respuestas" class="options"></a> <a href="javascript:void(0);" alt="Editar" title="Editar" class="edit"></a> <?php } ?><?php if (  \Util\UserSession::isDeletePrivilege() ){ ?><a href="javascript:void(0);" alt="Eliminar" title="Eliminar" class="delete"></a> <?php } ?>'
            }
        ],
        "iDisplayLength": 10
    } ); 
    
    
    editorUnidades = new $.fn.dataTable.Editor( {
        ajax: "<?php echo $this->serverUrl()?>/tcontent/unidadinformacion/update-row",
        table: "#unidades_table",
        idSrc:  'uni_inf_id',
        fields: [ {
	                label: "Id:",
	                name: "uni_inf_id"
	            }, {
	                label: "Titulo:",
	                name: "uni_inf_titulo"
	            }, {
	                label: "Orden:",
	                name: "lec_ele_orden"
	            }
	        ]
	    } );
	
	// Activate an inline edit on click of a table cell
    $('#unidades_table').on( 'click', 'td', function (e) { 
        editorUnidades.inline( this , {
            submitOnBlur: true
        });
    } );
    
      
} );
</script>