<div class="control seccion_titulo">
		<h3>Units</h3>
		<a alt="Cancel" title="Cancel" href="list?mid=<?php echo $this->mid; ?>&lid=<?php echo $this->lid; ?>" class="cancel">Cancel</a>
</div>
<form method="post" action="#" name="form_unidad" id="form_unidad" class="new_edit">
    <table cellpadding="0" cellspacing="0" border="0" class="form_table" align = "center">
	<tbody>
            <tr>
            	<td align="right">Tipo</td>
                <td align="left">
                    <select name="tipo">
                        <option value="1" <?php if ($this->unidad['uni_inf_tip_id'] == 1){echo 'selected="selected"'; } ?>>Content</option>
                        <option value="2" <?php if ($this->unidad['uni_inf_tip_id'] == 2){echo 'selected="selected"'; } ?>>Match</option>
                        <option value="3" <?php if ($this->unidad['uni_inf_tip_id'] == 3){echo 'selected="selected"'; } ?>>Multiple Answer</option>
                        <option value="4" <?php if ($this->unidad['uni_inf_tip_id'] == 4){echo 'selected="selected"'; } ?>>Multiple option with only response</option>
                        <option value="5" <?php if ($this->unidad['uni_inf_tip_id'] == 5){echo 'selected="selected"'; } ?>>True/False</option>
                        <option value="6" <?php if ($this->unidad['uni_inf_tip_id'] == 5){echo 'selected="selected"'; } ?>>Content with options</option>
                    </select>
                </td>
            </tr>
            <tr>
            	<td align="right">Instruction</td>
                <td align="left">
                	<input type="text" name="instruccion" value="<?php echo $this->unidad['uni_inf_instruccion']; ?>" />
                </td>
            </tr>
            <tr>
            	<td align="right">Instruction Audio</td>
                <td align="left">
                    <input type="file" name="instruccion_audio_file" id="instruccion_audio_file"><br>
                    <span class="urlsForm" id="urlsFormInstruccionAudio">
                        <?php if ( $this->unidad['uni_inf_instruccion_audio'] != '' ){ ?>
                        <audio controls><source src="https://s3.amazonaws.com/nutrifami/<?php echo $this->unidad['uni_inf_instruccion_audio']; ?>" type="audio/mpeg">Explorador no reproduce audio</audio>
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('instruccion_audio_file_url', 'urlsFormInstruccionAudio');" class="delete" src="/img/icons/cancel.png">
                        <?php } ?>
                    </span>
                    <input type="hidden" id="instruccion_audio_file_url" name="instruccion_audio" value="<?php echo $this->unidad['uni_inf_instruccion_audio']; ?>" />
                </td>
            </tr>
            <tr>
            	<td align="right">"Answer"</td>
                <td align="left">
                	<input type="text" name="pregunta" value="<?php echo $this->unidad['uni_inf_titulo']; ?>" />
                </td>
            </tr>
            <tr>
            	<td align="right">Text</td>
                <td align="left">
                    <textarea name="texto"><?php echo $this->unidad['uni_inf_texto']; ?></textarea>
                </td>
            </tr>
            <tr>
            	<td align="right">Audio</td>
                <td align="left">
                    <input type="file" name="audio_file" id="audio_file"><br>
                    <span class="urlsForm" id="urlsFormAudio">
                        <?php if ( $this->unidad['uni_inf_audio'] != '' ){ ?>
                        <audio controls><source src="https://s3.amazonaws.com/nutrifami/<?php echo $this->unidad['uni_inf_audio']; ?>" type="audio/mpeg">Explorador no reproduce audio</audio>
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('audio_file_url', 'urlsFormAudio');" class="delete" src="/img/icons/cancel.png">
                        <?php } ?>
                    </span>
                    <input type="hidden" id="audio_file_url" name="audio" value="<?php echo $this->unidad['uni_inf_audio']; ?>" />
                </td>
            </tr>
           <tr>
            	<td align="right">Image</td>
                <td align="left">
                    <input type="file" name="imagen_file" id="imagen_file" onchange="loadFileAsURL(this.files[0], 'image_1')"><br>
                    <span class="urlsForm" id="urlsFormImagen">
                        <?php if ( $this->unidad['uni_inf_imagen'] != '' ){ ?>
                        <div class="container_cropper">
                        <img class="img_cropper" id="image_1" src="https://s3.amazonaws.com/nutrifami/<?php echo $this->unidad['uni_inf_imagen']; ?>">
                        </div>
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('image_file_url', 'urlsFormImagen');" class="delete" src="/img/icons/cancel.png">
                        <?php }else { ?>
                        <div class="container_cropper">
                        <img class="img_cropper" id="image_1" src="">
                        </div>
                        <!--img width="200" src="https://s3.amazonaws.com/nutrifami/<?php echo $this->unidad['uni_inf_imagen']; ?>">
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('image_file_url', 'urlsFormImagen');" class="delete" src="/img/icons/cancel.png"-->
                        <?php } ?>
                    </span>
                    <input type="hidden" id="image_file_url" name="imagen" value="<?php echo $this->unidad['uni_inf_imagen']; ?>" />
                </td>
            </tr>
            <tr>
            	<td align="right"></td>
                <td align="left">
                    <input type="button" id="guardar_unidad" value="Save" />
                	<input type="hidden" name="id" value="<?php echo $this->id; ?>">
                        <input type="hidden" name="lid" value="<?php echo $this->lid; ?>">
                        <input type="hidden" name="mid" value="<?php echo $this->mid; ?>">
                </td>
            </tr>
        </tbody>
	</table>
</form>


<script type="text/javascript" src="/lib/cropper/cropper.js"></script>
<script type="text/javascript">

  nutrifami_aws.s3.load();
  
  var carga = 0;
  var image_cropped = '';
  
    $('#guardar_unidad').on("click", function(){ 
      sendForm();
  });
  
  function sendForm() {
    openOverlayLoad();
    uploadImage(document.getElementById('imagen_file'), document.getElementById('image_file_url').value, 'training/images/', $('#image_file_url'), function(){
        uploadInputFile(document.getElementById('audio_file'), 'training/audios/', $('#audio_file_url'), function(){
            uploadInputFile(document.getElementById('instruccion_audio_file'), 'training/audios/', $('#instruccion_audio_file_url'), function(){
                if ( carga == 0){
                    carga = 1;
                    $('#form_unidad').attr('action', "save");
                    $("#form_unidad").submit();
                }
            });
        });
    });    
  };
  
  function uploadInputFile (objectFile, cloudFolder, nameInput, callback) {
        callback = callback || function(){};
        if (objectFile.files.length == 0){
             callback();
        }else {
            var newFile = objectFile.files[0];
            var fileName = getFileName(newFile.name);   // Nombre del archivo en S3
            nameInput.val(cloudFolder+fileName);
            nutrifami_aws.s3.uploadFile(newFile,cloudFolder,fileName, function(){
                callback();
            });
        }
        /*callback();*/
  }
  
  
    
  function uploadImage (objectFile, fileName, cloudFolder, nameInput, callback){
        callback = callback || function(){}; console.log(objectFile.files.length);
        if (objectFile.files.length === 0 && fileName === ''){
             callback();
        }else {
            var newFile = '';
            if (objectFile.files.length === 0){
                newFile = dataURLtoFile(image_cropped, fileName);
            }else {
                newFile = dataURLtoFile(image_cropped, objectFile.files[0].name);
            }
            if (newFile.length === 0){
                callback();
           }else {
               var fileName = getFileName(newFile.name);   // Nombre del archivo en S3
               nameInput.val(cloudFolder+fileName);
               nutrifami_aws.s3.uploadFile(newFile,cloudFolder,fileName, function(){
                   callback();
               });
           }
       }
        
  }
  
  
  function removeFile (urlInput, objectInput) {
      $('#'+urlInput).val('');
      $('#'+objectInput).html('');
  }
  
  function seleccionarIcono (id) {
      $('.leccion_icono').removeClass('icon_selected');
      $('.leccion_icono_'+id).addClass('icon_selected');
      $('#icono_numero').val(id);
  }
  
  
  
      $('#image_1').cropper({
        /*viewMode: 3,
        dragMode: 'move',
        autoCropArea: 1,
        restore: false,
        modal: false,
        guides: false,
        highlight: false,
        cropBoxMovable: false,
        cropBoxResizable: false,*/
        crop: function(e) {
            // Output the result data for cropping image.
            var croppedCanvas = $(this).cropper('getCroppedCanvas', { width: 1024, height: 204 });
            image_cropped = croppedCanvas.toDataURL();
            //console.log(image_cropped);
        }
      }); 

   
</script>

<style>
    
        .container_cropper {
            height: 102px;
            width: 512px;
        }

        /* Limit image width to avoid overflow the container */
        .img_cropper {
          max-width: 100%; /* This rule is very important, please do not ignore this! */
        }
    
</style>