<div class="control seccion_titulo">
		<h3>Options or answerss</h3>
		<a alt="Cancel" title="Cancel" href="list?mid=<?php echo $this->mid; ?>&lid=<?php echo $this->lid; ?>&uid=<?php echo $this->uid; ?>" class="cancel">Cancel</a>
</div>
<form method="post" action="#" name="form_opcion" id="form_opcion" class="new_edit">
    <table cellpadding="0" cellspacing="0" border="0" class="form_table" align = "center">
	<tbody>
            
            <tr>
                <td align="right">Text
                    <div class="preview" style="display: none;">
                        <p class="error">It is recommended not to exceed 120 characters</p>
                        <div class="card">
                            <img class="image-2" src="">
                            <p id="card-text" class="text"></p>
                        </div>
                    </div>
                </td>
                <td align="left">
                    <textarea name="texto" onchange="countCharacters(this.value);" id="texto_opcion"><?php echo $this->opcion['uni_inf_opc_texto']; ?></textarea>
                </td>
            </tr>
            <tr>
            	<td align="right">Audio</td>
                <td align="left">
                    <input type="file" name="audio_file" id="audio_file"><br>
                    <span class="urlsForm" id="urlsFormAudio">
                        <?php if ( $this->opcion['uni_inf_opc_audio'] != '' ){ ?>
                        <audio controls><source src="https://s3.amazonaws.com/nutrifami/<?php echo $this->opcion['uni_inf_opc_audio']; ?>" type="audio/mpeg">Explorador no reproduce audio</audio>
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('audio_file_url', 'urlsFormAudio');" class="delete" src="/img/icons/cancel.png">
                        <?php } ?>
                    </span>
                    <input type="hidden" id="audio_file_url" name="audio" value="<?php echo $this->opcion['uni_inf_opc_audio']; ?>" />
                </td>
            </tr>
            <tr>
            	<td align="right">Image</td>
                <td align="left">
                    <input type="file" name="imagen_file" id="imagen_file" onchange="loadFileAsURL(this.files[0], 'image_1')"><br>
                    <span class="urlsForm" id="urlsFormImagen">
                        <?php if ( $this->opcion['uni_inf_opc_media'] != '' ){ ?>
                        <div class="container_cropper">
                        <img class="img_cropper" id="image_1" src="https://s3.amazonaws.com/nutrifami/<?php echo $this->opcion['uni_inf_opc_media']; ?>">
                        </div>
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('image_file_url', 'urlsFormImagen');" class="delete" src="/img/icons/cancel.png">
                        <?php }else { ?>
                        <div class="container_cropper">
                        <img class="img_cropper" id="image_1" src="">
                        </div>
                        <!--img width="200" src="https://s3.amazonaws.com/nutrifami/<?php echo $this->unidad['uni_inf_imagen']; ?>">
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('image_file_url', 'urlsFormImagen');" class="delete" src="/img/icons/cancel.png"-->
                        <?php } ?>
                        <?php /* if ( $this->opcion['uni_inf_opc_media'] != '' ){ ?>
                        <img width="200" src="https://s3.amazonaws.com/nutrifami/<?php echo $this->opcion['uni_inf_opc_media']; ?>">
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('image_file_url', 'urlsFormImagen');" class="delete" src="/img/icons/cancel.png">
                        <?php }*/ ?>
                    </span>
                    <input type="hidden" id="image_file_url" name="imagen" value="<?php echo $this->opcion['uni_inf_opc_media']; ?>" />
                </td>
            </tr>
            <tr>
            	<td align="right">Rigth answer</td>
                <td align="left">
                    <select name="correcta">
                        <option value="1" <?php if ($this->opcion['uni_inf_x_opc_correcta'] == 1){echo 'selected="selected"'; } ?>>Correct</option>
                        <option value="0" <?php if ($this->opcion['uni_inf_x_opc_correcta'] == 0){echo 'selected="selected"'; } ?>>incorrect</option>
                    </select>
                </td>
            </tr>
            <tr>
            	<td align="right">Feedback</td>
                <td align="left">
                    <textarea name="feedback"><?php echo $this->opcion['uni_inf_opc_feedback']; ?></textarea>
                </td>
            </tr>
            <tr>
            	<td align="right">Feedback Audio</td>
                <td align="left">
                    <input type="file" name="feedback_audio_file" id="feedback_audio_file"><br>
                    <span class="urlsForm" id="urlsFormFeedbackAudio">
                        <?php if ( $this->opcion['uni_inf_opc_feedback_audio'] != '' ){ ?>
                        <audio controls><source src="https://s3.amazonaws.com/nutrifami/<?php echo $this->opcion['uni_inf_opc_feedback_audio']; ?>" type="audio/mpeg">Explorador no reproduce audio</audio>
                        <img class="delete" alt="Delete" title="Delete" onclick="removeFile('feedback_audio_file_url', 'urlsFormFeedbackAudio');" class="delete" src="/img/icons/cancel.png">
                        <?php } ?>
                    </span>
                    <input type="hidden" id="feedback_audio_file_url" name="feedback_audio" value="<?php echo $this->opcion['uni_inf_opc_feedback_audio']; ?>" />
                </td>
            </tr>
            <tr>
            	<td align="right"></td>
                <td align="left">
                    <input type="button" id="guardar_unidad" value="Save" />
                	<input type="hidden" name="id" value="<?php echo $this->id; ?>">
                        <input type="hidden" name="uid" value="<?php echo $this->uid; ?>">
                        <input type="hidden" name="lid" value="<?php echo $this->lid; ?>">
                        <input type="hidden" name="mid" value="<?php echo $this->mid; ?>">
                </td>
            </tr>
        </tbody>
	</table>
</form>

<script type="text/javascript" src="/lib/cropper/cropper.js"></script>
<script type="text/javascript">

  nutrifami_aws.s3.load();
  
  var carga = 0;
  var image_cropped = '';
  
    $('#guardar_unidad').on("click", function(){ 
      sendForm();
  });
  
  function sendForm() {
    openOverlayLoad();
    uploadImage(document.getElementById('imagen_file'), document.getElementById('image_file_url').value, 'training/images/', $('#image_file_url'), function(){
        uploadInputFile(document.getElementById('audio_file'), 'training/audios/', $('#audio_file_url'), function(){
            uploadInputFile(document.getElementById('feedback_audio_file'), 'training/audios/', $('#feedback_audio_file_url'), function(){
                if ( carga == 0){
                    carga = 1;
                    $('#form_opcion').attr('action', "save");
                    $("#form_opcion").submit();
                }
            });
        });
    });    
  };
  
  function uploadInputFile (objectFile, cloudFolder, nameInput, callback) {
        callback = callback || function(){}; 
        if (objectFile.files.length == 0){
             callback();
        }else {
            var newFile = objectFile.files[0];
            var fileName = getFileName(newFile.name);   // Nombre del archivo en S3
            nameInput.val(cloudFolder+fileName);
            nutrifami_aws.s3.uploadFile(newFile,cloudFolder,fileName, function(){
                callback();
            });
        }
        /*callback();*/
  }
  
  
  function uploadImage (objectFile, fileName, cloudFolder, nameInput, callback){
        callback = callback || function(){}; console.log(objectFile.files.length);
        if (objectFile.files.length === 0 && fileName === ''){
             callback();
        }else {
            var newFile = '';
            if (objectFile.files.length === 0){
                newFile = dataURLtoFile(image_cropped, fileName);
            }else {
                newFile = dataURLtoFile(image_cropped, objectFile.files[0].name);
            }
            if (newFile.length === 0){
                callback();
           }else {
               var fileName = getFileName(newFile.name);   // Nombre del archivo en S3
               nameInput.val(cloudFolder+fileName);
               nutrifami_aws.s3.uploadFile(newFile,cloudFolder,fileName, function(){
                   callback();
               });
           }
       }
        
  }
  
  
  
  function removeFile (urlInput, objectInput) {
      $('#'+urlInput).val('');
      $('#'+objectInput).html('');
  }
  
  
        $('#image_1').cropper({
        /*viewMode: 3,
        dragMode: 'move',
        autoCropArea: 1,
        restore: false,
        modal: false,
        guides: false,
        highlight: false,
        cropBoxMovable: false,
        cropBoxResizable: false,*/
        crop: function(e) {
            // Output the result data for cropping image.
            var croppedCanvas = $(this).cropper('getCroppedCanvas', { width: 300, height: 216 });
            image_cropped = croppedCanvas.toDataURL();
            //console.log(image_cropped);
        }
      }); 
      
      
      function countCharacters (contenido) { 
          var idTag = 'texto_opcion';
          var number = 120;
          var regex = /(&nbsp;|<([^>]+)>)/ig;
          $(".card p").html(contenido); 
          $(".card p p").unwrap();
          var result = $(".card p").html();
          result = result.replace(regex, "");
          if ( result.length > number ) { 
              $('.preview').show();
              $('.error').show();
              console.log(result.length);
          }else {
              $('.error').hide();
          } 
      }

   
</script>


<style>
    
        .container_cropper {
            height: 216px;
            width: 300px;
        }

        /* Limit image width to avoid overflow the container */
        .img_cropper {
          max-width: 100%; /* This rule is very important, please do not ignore this! */
        }
    
        .card {
            background-color: #fff;
            border: 1px solid #dcdcdc;
            border-radius: 10px;
            height: 100px;
            width: 200px;
            margin: 0 10px 15px;
            overflow: hidden;
            position: relative;
            cursor: pointer;
            background: url(https://s3.amazonaws.com/nutrifami/<?php echo $this->opcion['uni_inf_opc_media']; ?>);
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center; 
            
            
        }
        .card img {
            
        }
        .card .text, .card p{
            color: #fff;
            text-align: center;
            background:rgb(0,0,0);  
            background: transparent\9;  
            background:rgba(0,0,0,0.4);  
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#66000000,endColorstr=#66000000);  
            zoom: 1; 
        }
</style>