<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Commodity\Module'                        => __DIR__ . '/Module.php',
    'Commodity\Controller\IndexController' => __DIR__ . '/src/Commodity/Controller/IndexController.php',
    'CommodityTest\Framework\TestCase'        => __DIR__ . '/tests/Commodity/Framework/TestCase.php',
    'CommodityTest\SampleTest'                => __DIR__ . '/tests/Commodity/SampleTest.php',
);
